### ISSUE TITLE
the 1.5.0 release seems to be broken

### ISSUE THREAD

**Issue by anshul** [theniceboy/coc-flutter-tools#13]
**Describe the bug**
`:CocCommand flutter.toggleOutline`  does not work in the 1.5.0 package published to npm.   Command registration seems to be only working for `flutter.run` but not for the outline related commands.

**To Reproduce**
* Install 1.5.0 using `:CocInstall coc-flutter@1.5.0` and no outline related functionality is accessible.
* Downgrade to 1.4.1 using `:CocInstall coc-flutter@1.4.1` and everything works as expected.

**Expected behavior**
`:CocCommand flutter.toggleOutline` should work in the latest relase.

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.10
 - Neovim:  nvim 0.4.4

**Comment by theniceboy** [comment]
Thank you for reporting! I think some of the changes ported from coc-flutter might have broken things. I'll look into it this today.

**Comment by theniceboy** [comment]
Fixed! Thanks!
