### ISSUE TITLE
PR for the outline feature

### ISSUE THREAD

**Issue by Kavantix** [theniceboy/coc-flutter-tools#14]
Hey @theniceboy, we were looking into making something for the flutter outline and I stumbled upon your fork and saw you already made one.
The gif looks really good it would be nice if you could make it into a PR to the main project such that everyone can use it :)

@iamcco FYI

**Comment by iamcco** [comment]
It will be great if you can make a pr for it.

**Comment by Kavantix** [comment]
In the `feature/outline` branch of the main repo I got it to work with the latest version.
You can use that as a starting point

**Comment by theniceboy** [comment]
@Kavantix @iamcco Yeah, of course. Can you add me as a collaborator, please? I think that'll make things easier as I can easily fix stuff within the outline feature. Thanks!

**Comment by Kavantix** [comment]
@chemzqm @fannheyward perhaps we can also extract the tree view component to put it directly in coc.nvim?

**Comment by Kavantix** [comment]
@theniceboy either way it's best to work with PR's :)

**Comment by theniceboy** [comment]
@Kavantix yes I'll be submitting PRs for sure, it would be my pleasure to join this project as I depend on it so much.

**Comment by Kavantix** [comment]
Cool! I'll leave the contributor part up to @iamcco to decide.
But could you branch of `feature/outline` and create a draft PR from there then we can continue any discussions there

**Comment by iamcco** [comment]
@theniceboy I have invite you join the repo, let's make it better.

**Comment by theniceboy** [comment]
@Kavantix Will do!

**Comment by theniceboy** [comment]
@iamcco Thanks!
