### ISSUE TITLE
How to disable previewLsp

### ISSUE THREAD

**Issue by nima-dvlp** [theniceboy/coc-flutter-tools#15]
As described [here](https://github.com/Dart-Code/Dart-Code/issues/3102) disabling `previewLsp` will increase performance, I can't find a way to do this, any suggestion?

**Comment by wizawuza** [comment]
This may help:
In `settings.json`, change the `dart.previewLsp` entry to false. For example:
`"dart.previewLsp": false`

**Comment by nima-dvlp** [comment]
```
vim version: NVIM v0.5.0-dev+1330-gd16e9d8ed
node version: v16.2.0
coc.nvim version: 0.0.80-46353b786b
coc.nvim directory: /home/nima/.local/share/nvim/plugged/coc.nvim
term: xterm-256color
platform: linux

✓ coc-flutter-tools Current version 1.6.1 is up to date.

[✓] Flutter (Channel stable, 2.2.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.5)
[✓] Connected device (3 available)
```
![Screenshot_20210607_090154](https://user-images.githubusercontent.com/73692252/120959446-03900700-c76f-11eb-8706-bafe660efa0b.png)

I can confirm that `"flutter.trace.server": "verbose"` will cause the problem, and I face the problem in just a few minutes of coding!
