### ISSUE TITLE
Why forking the original repo ?

### ISSUE THREAD

**Issue by AdrienLemaire** [theniceboy/coc-flutter-tools#21]
Arriving on your github repo, I see 

> This branch is [73 commits ahead](https://github.com/theniceboy/coc-flutter-tools/compare/iamcco:coc-flutter:master...master), [62 commits behind](https://github.com/theniceboy/coc-flutter-tools/compare/master...iamcco:coc-flutter:master) iamcco:master.

Your description implies that coc-flutter is not being maintained anymore and you took over, but that doesn't seem to be the case.
Wouldn't it be in the best interest of the flutter coc.nvim community to concentrate the efforts on one repo ?

I'm confused as to which plugin I should go with :)

**Comment by theniceboy** [comment]
Hmmmm I'm not how you got the message that `coc-flutter` is not being maintained and I took over... but anyways, FYI
- `coc-flutter` is still being maintained with great efforts.
- `coc-flutter-tools` is an active fork of `coc-flutter` with some of the features that are immature to be merged to the main branch.
- If you're plugin searching, you might want to look at https://github.com/akinsho/flutter-tools.nvim as well :)
