### ISSUE TITLE
Command to toggle debug banner on emulator/devices

### ISSUE THREAD

**Issue by unknowledgeable** [theniceboy/coc-flutter-tools#4]
Would be great to be able to do this from vim instead of going in to DevTools and clicking around to get it to go away when designing top of screen UI.

Extra unnecessary QoL bonus would be to show an indicator on the statusline if the app is running in debug mode but the banner is disabled. Maybe a nerdfont/devicon symbol or something?

**Comment by theniceboy** [comment]
It would be great but I don’t think it’s possible though. One workaround is to add `debugShowCheckedModeBanner: false, ` to `MaterialApp`.

**Comment by unknowledgeable** [comment]
Cool just a thought! Thanks for the tip!
