### ISSUE TITLE
Noob Usage Questions :)

### ISSUE THREAD

**Issue by brianegan-phntm** [theniceboy/coc-flutter-tools#8]
Heya! Getting my Vim setup for Flutter dev again. Thanks so much to the original authors and to you for the continued improvement.

  1. Is there anywhere I can see a list of all Dart errors for a project, instead of just the errors for a given file? Intellij has a "Dart Analysis" window that lists all problems for a project, hoping this plugin has something like that! Helpful during refactors or when applying new linting rules :)
  2. Is there any way to configure the formatter to use 120 instead of 80 chars? It looks like you can do this with the dartfmt options from the official dart-vim plugin, but it's a bit slow for me and wanted to see if the Coc tools had this ability, although. I didn't see it.

Appreciate any time you have to answer! Thanks so much :)

**Comment by theniceboy** [comment]
Don't worry.
1. `:CocList diagnostics`
2. If you use [dart-vim-plugin](https://github.com/dart-lang/dart-vim-plugin), put this in your vimrc: `let g:dartfmt_options = ["-l 120"]`

**Comment by theniceboy** [comment]
Feel free to reopen

**Comment by brianegan-phntm** [comment]
Haha, dang it -- i was using `:CocDiagnostics` rather than `:CocList diagnostics`. 

Thanks again :)
